/*
 * This file is generated by jOOQ.
 */
package com.mvs.repo.routines;


import com.mvs.repo.Public;

import org.jooq.Field;
import org.jooq.Parameter;
import org.jooq.impl.AbstractRoutine;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AddRole extends AbstractRoutine<Integer> {

    private static final long serialVersionUID = 1L;

    /**
     * The parameter <code>public.add_role.RETURN_VALUE</code>.
     */
    public static final Parameter<Integer> RETURN_VALUE = Internal.createParameter("RETURN_VALUE", SQLDataType.INTEGER, false, false);

    /**
     * The parameter <code>public.add_role.p_name</code>.
     */
    public static final Parameter<String> P_NAME = Internal.createParameter("p_name", SQLDataType.VARCHAR, false, false);

    /**
     * The parameter <code>public.add_role.p_access_level</code>.
     */
    public static final Parameter<Long> P_ACCESS_LEVEL = Internal.createParameter("p_access_level", SQLDataType.BIGINT, false, false);

    /**
     * Create a new routine call instance
     */
    public AddRole() {
        super("add_role", Public.PUBLIC, SQLDataType.INTEGER);

        setReturnParameter(RETURN_VALUE);
        addInParameter(P_NAME);
        addInParameter(P_ACCESS_LEVEL);
    }

    /**
     * Set the <code>p_name</code> parameter IN value to the routine
     */
    public void setPName(String value) {
        setValue(P_NAME, value);
    }

    /**
     * Set the <code>p_name</code> parameter to the function to be used with a
     * {@link org.jooq.Select} statement
     */
    public AddRole setPName(Field<String> field) {
        setField(P_NAME, field);
        return this;
    }

    /**
     * Set the <code>p_access_level</code> parameter IN value to the routine
     */
    public void setPAccessLevel(Long value) {
        setValue(P_ACCESS_LEVEL, value);
    }

    /**
     * Set the <code>p_access_level</code> parameter to the function to be used
     * with a {@link org.jooq.Select} statement
     */
    public AddRole setPAccessLevel(Field<Long> field) {
        setField(P_ACCESS_LEVEL, field);
        return this;
    }
}
