/*
 * This file is generated by jOOQ.
 */
package com.mvs.repo.routines;


import com.mvs.repo.Public;

import java.time.LocalDateTime;

import org.jooq.Parameter;
import org.jooq.impl.AbstractRoutine;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MinPartitioner extends AbstractRoutine<java.lang.Void> {

    private static final long serialVersionUID = 1L;

    /**
     * The parameter <code>public.min_partitioner.t</code>.
     */
    public static final Parameter<String> T = Internal.createParameter("t", SQLDataType.CLOB, false, false);

    /**
     * The parameter <code>public.min_partitioner.field</code>.
     */
    public static final Parameter<String> FIELD = Internal.createParameter("field", SQLDataType.CLOB, false, false);

    /**
     * The parameter <code>public.min_partitioner.d1</code>.
     */
    public static final Parameter<LocalDateTime> D1 = Internal.createParameter("d1", SQLDataType.LOCALDATETIME(6), false, false);

    /**
     * The parameter <code>public.min_partitioner.d2</code>.
     */
    public static final Parameter<LocalDateTime> D2 = Internal.createParameter("d2", SQLDataType.LOCALDATETIME(6), false, false);

    /**
     * Create a new routine call instance
     */
    public MinPartitioner() {
        super("min_partitioner", Public.PUBLIC);

        addInParameter(T);
        addInParameter(FIELD);
        addInParameter(D1);
        addInParameter(D2);
    }

    /**
     * Set the <code>t</code> parameter IN value to the routine
     */
    public void setT(String value) {
        setValue(T, value);
    }

    /**
     * Set the <code>field</code> parameter IN value to the routine
     */
    public void setField(String value) {
        setValue(FIELD, value);
    }

    /**
     * Set the <code>d1</code> parameter IN value to the routine
     */
    public void setD1(LocalDateTime value) {
        setValue(D1, value);
    }

    /**
     * Set the <code>d2</code> parameter IN value to the routine
     */
    public void setD2(LocalDateTime value) {
        setValue(D2, value);
    }
}
