/*
 * This file is generated by jOOQ.
 */
package com.mvs.repo.routines;


import com.mvs.repo.Public;

import org.jooq.Field;
import org.jooq.Parameter;
import org.jooq.impl.AbstractRoutine;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RevokeUserRole extends AbstractRoutine<Integer> {

    private static final long serialVersionUID = 1L;

    /**
     * The parameter <code>public.revoke_user_role.RETURN_VALUE</code>.
     */
    public static final Parameter<Integer> RETURN_VALUE = Internal.createParameter("RETURN_VALUE", SQLDataType.INTEGER, false, false);

    /**
     * The parameter <code>public.revoke_user_role.p_user_id</code>.
     */
    public static final Parameter<Long> P_USER_ID = Internal.createParameter("p_user_id", SQLDataType.BIGINT, false, false);

    /**
     * The parameter <code>public.revoke_user_role.p_role_id</code>.
     */
    public static final Parameter<Long> P_ROLE_ID = Internal.createParameter("p_role_id", SQLDataType.BIGINT, false, false);

    /**
     * Create a new routine call instance
     */
    public RevokeUserRole() {
        super("revoke_user_role", Public.PUBLIC, SQLDataType.INTEGER);

        setReturnParameter(RETURN_VALUE);
        addInParameter(P_USER_ID);
        addInParameter(P_ROLE_ID);
    }

    /**
     * Set the <code>p_user_id</code> parameter IN value to the routine
     */
    public void setPUserId(Long value) {
        setValue(P_USER_ID, value);
    }

    /**
     * Set the <code>p_user_id</code> parameter to the function to be used with
     * a {@link org.jooq.Select} statement
     */
    public RevokeUserRole setPUserId(Field<Long> field) {
        setField(P_USER_ID, field);
        return this;
    }

    /**
     * Set the <code>p_role_id</code> parameter IN value to the routine
     */
    public void setPRoleId(Long value) {
        setValue(P_ROLE_ID, value);
    }

    /**
     * Set the <code>p_role_id</code> parameter to the function to be used with
     * a {@link org.jooq.Select} statement
     */
    public RevokeUserRole setPRoleId(Field<Long> field) {
        setField(P_ROLE_ID, field);
        return this;
    }
}
