#!/bin/bash

repoDir=$(pwd)
git remote rename origin github
git branch -m base

git remote add saba-template http://scg.otcsaba.ir/m.vahidsafa/microservicetemplate.git
git fetch saba-template
git switch -c saba-base saba-template/master

read -p "Enter Project name in gitlab: " repository
git remote add origin http://scg.otcsaba.ir/m.vahidsafa/%repository%
git fetch origin
git switch -c master origin/master

cd ..
mv "$repoDir" "$repository"