/*
 * This file is generated by jOOQ.
 */
package com.mvs.repo.tables.records;


import com.mvs.repo.tables.GetRoleList;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GetRoleListRecord extends TableRecordImpl<GetRoleListRecord> implements Record2<Long, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.get_role_list.id</code>.
     */
    public GetRoleListRecord setId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.get_role_list.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.get_role_list.name</code>.
     */
    public GetRoleListRecord setName(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.get_role_list.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row2<Long, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    public Row2<Long, String> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return GetRoleList.GET_ROLE_LIST.ID;
    }

    @Override
    public Field<String> field2() {
        return GetRoleList.GET_ROLE_LIST.NAME;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getName();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getName();
    }

    @Override
    public GetRoleListRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public GetRoleListRecord value2(String value) {
        setName(value);
        return this;
    }

    @Override
    public GetRoleListRecord values(Long value1, String value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached GetRoleListRecord
     */
    public GetRoleListRecord() {
        super(GetRoleList.GET_ROLE_LIST);
    }

    /**
     * Create a detached, initialised GetRoleListRecord
     */
    public GetRoleListRecord(Long id, String name) {
        super(GetRoleList.GET_ROLE_LIST);

        setId(id);
        setName(name);
    }

    /**
     * Create a detached, initialised GetRoleListRecord
     */
    public GetRoleListRecord(com.mvs.repo.tables.pojos.GetRoleList value) {
        super(GetRoleList.GET_ROLE_LIST);

        if (value != null) {
            setId(value.getId());
            setName(value.getName());
        }
    }
}
