/*
 * This file is generated by jOOQ.
 */
package com.mvs.repo.tables.records;


import com.mvs.repo.tables.GetUserRoles;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Row1;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GetUserRolesRecord extends TableRecordImpl<GetUserRolesRecord> implements Record1<Long> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.get_user_roles.role_id</code>.
     */
    public GetUserRolesRecord setRoleId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.get_user_roles.role_id</code>.
     */
    public Long getRoleId() {
        return (Long) get(0);
    }

    // -------------------------------------------------------------------------
    // Record1 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row1<Long> fieldsRow() {
        return (Row1) super.fieldsRow();
    }

    @Override
    public Row1<Long> valuesRow() {
        return (Row1) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return GetUserRoles.GET_USER_ROLES.ROLE_ID;
    }

    @Override
    public Long component1() {
        return getRoleId();
    }

    @Override
    public Long value1() {
        return getRoleId();
    }

    @Override
    public GetUserRolesRecord value1(Long value) {
        setRoleId(value);
        return this;
    }

    @Override
    public GetUserRolesRecord values(Long value1) {
        value1(value1);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached GetUserRolesRecord
     */
    public GetUserRolesRecord() {
        super(GetUserRoles.GET_USER_ROLES);
    }

    /**
     * Create a detached, initialised GetUserRolesRecord
     */
    public GetUserRolesRecord(Long roleId) {
        super(GetUserRoles.GET_USER_ROLES);

        setRoleId(roleId);
    }

    /**
     * Create a detached, initialised GetUserRolesRecord
     */
    public GetUserRolesRecord(com.mvs.repo.tables.pojos.GetUserRoles value) {
        super(GetUserRoles.GET_USER_ROLES);

        if (value != null) {
            setRoleId(value.getRoleId());
        }
    }
}
