/*
 * This file is generated by jOOQ.
 */
package com.mvs.repo.tables.records;


import com.mvs.repo.tables.TRole;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TRoleRecord extends UpdatableRecordImpl<TRoleRecord> implements Record4<Long, LocalDateTime, LocalDateTime, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.t_role.id</code>.
     */
    public TRoleRecord setId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.t_role.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.t_role.created_at</code>.
     */
    public TRoleRecord setCreatedAt(LocalDateTime value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.t_role.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(1);
    }

    /**
     * Setter for <code>public.t_role.updated_at</code>.
     */
    public TRoleRecord setUpdatedAt(LocalDateTime value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.t_role.updated_at</code>.
     */
    public LocalDateTime getUpdatedAt() {
        return (LocalDateTime) get(2);
    }

    /**
     * Setter for <code>public.t_role.name</code>.
     */
    public TRoleRecord setName(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.t_role.name</code>.
     */
    public String getName() {
        return (String) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row4<Long, LocalDateTime, LocalDateTime, String> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    @Override
    public Row4<Long, LocalDateTime, LocalDateTime, String> valuesRow() {
        return (Row4) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return TRole.T_ROLE.ID;
    }

    @Override
    public Field<LocalDateTime> field2() {
        return TRole.T_ROLE.CREATED_AT;
    }

    @Override
    public Field<LocalDateTime> field3() {
        return TRole.T_ROLE.UPDATED_AT;
    }

    @Override
    public Field<String> field4() {
        return TRole.T_ROLE.NAME;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public LocalDateTime component2() {
        return getCreatedAt();
    }

    @Override
    public LocalDateTime component3() {
        return getUpdatedAt();
    }

    @Override
    public String component4() {
        return getName();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public LocalDateTime value2() {
        return getCreatedAt();
    }

    @Override
    public LocalDateTime value3() {
        return getUpdatedAt();
    }

    @Override
    public String value4() {
        return getName();
    }

    @Override
    public TRoleRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public TRoleRecord value2(LocalDateTime value) {
        setCreatedAt(value);
        return this;
    }

    @Override
    public TRoleRecord value3(LocalDateTime value) {
        setUpdatedAt(value);
        return this;
    }

    @Override
    public TRoleRecord value4(String value) {
        setName(value);
        return this;
    }

    @Override
    public TRoleRecord values(Long value1, LocalDateTime value2, LocalDateTime value3, String value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TRoleRecord
     */
    public TRoleRecord() {
        super(TRole.T_ROLE);
    }

    /**
     * Create a detached, initialised TRoleRecord
     */
    public TRoleRecord(Long id, LocalDateTime createdAt, LocalDateTime updatedAt, String name) {
        super(TRole.T_ROLE);

        setId(id);
        setCreatedAt(createdAt);
        setUpdatedAt(updatedAt);
        setName(name);
    }

    /**
     * Create a detached, initialised TRoleRecord
     */
    public TRoleRecord(com.mvs.repo.tables.pojos.TRole value) {
        super(TRole.T_ROLE);

        if (value != null) {
            setId(value.getId());
            setCreatedAt(value.getCreatedAt());
            setUpdatedAt(value.getUpdatedAt());
            setName(value.getName());
        }
    }
}
