/*
 * This file is generated by jOOQ.
 */
package com.mvs.repo.tables.records;


import com.mvs.repo.tables.TUserRoleDeleted;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TUserRoleDeletedRecord extends UpdatableRecordImpl<TUserRoleDeletedRecord> implements Record6<Long, LocalDateTime, LocalDateTime, Boolean, Long, Long> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.t_user_role_deleted.id</code>.
     */
    public TUserRoleDeletedRecord setId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.t_user_role_deleted.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.t_user_role_deleted.created_at</code>.
     */
    public TUserRoleDeletedRecord setCreatedAt(LocalDateTime value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.t_user_role_deleted.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(1);
    }

    /**
     * Setter for <code>public.t_user_role_deleted.updated_at</code>.
     */
    public TUserRoleDeletedRecord setUpdatedAt(LocalDateTime value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.t_user_role_deleted.updated_at</code>.
     */
    public LocalDateTime getUpdatedAt() {
        return (LocalDateTime) get(2);
    }

    /**
     * Setter for <code>public.t_user_role_deleted.deleted</code>.
     */
    public TUserRoleDeletedRecord setDeleted(Boolean value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.t_user_role_deleted.deleted</code>.
     */
    public Boolean getDeleted() {
        return (Boolean) get(3);
    }

    /**
     * Setter for <code>public.t_user_role_deleted.user_id</code>.
     */
    public TUserRoleDeletedRecord setUserId(Long value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>public.t_user_role_deleted.user_id</code>.
     */
    public Long getUserId() {
        return (Long) get(4);
    }

    /**
     * Setter for <code>public.t_user_role_deleted.role_id</code>.
     */
    public TUserRoleDeletedRecord setRoleId(Long value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>public.t_user_role_deleted.role_id</code>.
     */
    public Long getRoleId() {
        return (Long) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<Long, Boolean> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row6<Long, LocalDateTime, LocalDateTime, Boolean, Long, Long> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    @Override
    public Row6<Long, LocalDateTime, LocalDateTime, Boolean, Long, Long> valuesRow() {
        return (Row6) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return TUserRoleDeleted.T_USER_ROLE_DELETED.ID;
    }

    @Override
    public Field<LocalDateTime> field2() {
        return TUserRoleDeleted.T_USER_ROLE_DELETED.CREATED_AT;
    }

    @Override
    public Field<LocalDateTime> field3() {
        return TUserRoleDeleted.T_USER_ROLE_DELETED.UPDATED_AT;
    }

    @Override
    public Field<Boolean> field4() {
        return TUserRoleDeleted.T_USER_ROLE_DELETED.DELETED;
    }

    @Override
    public Field<Long> field5() {
        return TUserRoleDeleted.T_USER_ROLE_DELETED.USER_ID;
    }

    @Override
    public Field<Long> field6() {
        return TUserRoleDeleted.T_USER_ROLE_DELETED.ROLE_ID;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public LocalDateTime component2() {
        return getCreatedAt();
    }

    @Override
    public LocalDateTime component3() {
        return getUpdatedAt();
    }

    @Override
    public Boolean component4() {
        return getDeleted();
    }

    @Override
    public Long component5() {
        return getUserId();
    }

    @Override
    public Long component6() {
        return getRoleId();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public LocalDateTime value2() {
        return getCreatedAt();
    }

    @Override
    public LocalDateTime value3() {
        return getUpdatedAt();
    }

    @Override
    public Boolean value4() {
        return getDeleted();
    }

    @Override
    public Long value5() {
        return getUserId();
    }

    @Override
    public Long value6() {
        return getRoleId();
    }

    @Override
    public TUserRoleDeletedRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public TUserRoleDeletedRecord value2(LocalDateTime value) {
        setCreatedAt(value);
        return this;
    }

    @Override
    public TUserRoleDeletedRecord value3(LocalDateTime value) {
        setUpdatedAt(value);
        return this;
    }

    @Override
    public TUserRoleDeletedRecord value4(Boolean value) {
        setDeleted(value);
        return this;
    }

    @Override
    public TUserRoleDeletedRecord value5(Long value) {
        setUserId(value);
        return this;
    }

    @Override
    public TUserRoleDeletedRecord value6(Long value) {
        setRoleId(value);
        return this;
    }

    @Override
    public TUserRoleDeletedRecord values(Long value1, LocalDateTime value2, LocalDateTime value3, Boolean value4, Long value5, Long value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TUserRoleDeletedRecord
     */
    public TUserRoleDeletedRecord() {
        super(TUserRoleDeleted.T_USER_ROLE_DELETED);
    }

    /**
     * Create a detached, initialised TUserRoleDeletedRecord
     */
    public TUserRoleDeletedRecord(Long id, LocalDateTime createdAt, LocalDateTime updatedAt, Boolean deleted, Long userId, Long roleId) {
        super(TUserRoleDeleted.T_USER_ROLE_DELETED);

        setId(id);
        setCreatedAt(createdAt);
        setUpdatedAt(updatedAt);
        setDeleted(deleted);
        setUserId(userId);
        setRoleId(roleId);
    }

    /**
     * Create a detached, initialised TUserRoleDeletedRecord
     */
    public TUserRoleDeletedRecord(com.mvs.repo.tables.pojos.TUserRoleDeleted value) {
        super(TUserRoleDeleted.T_USER_ROLE_DELETED);

        if (value != null) {
            setId(value.getId());
            setCreatedAt(value.getCreatedAt());
            setUpdatedAt(value.getUpdatedAt());
            setDeleted(value.getDeleted());
            setUserId(value.getUserId());
            setRoleId(value.getRoleId());
        }
    }
}
