/*
 * This file is generated by jOOQ.
 */
package com.mvs.repo.tables;


import com.mvs.repo.Indexes;
import com.mvs.repo.Keys;
import com.mvs.repo.Public;
import com.mvs.repo.tables.records.TUserRoleRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row6;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TUserRole extends TableImpl<TUserRoleRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.t_user_role</code>
     */
    public static final TUserRole T_USER_ROLE = new TUserRole();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TUserRoleRecord> getRecordType() {
        return TUserRoleRecord.class;
    }

    /**
     * The column <code>public.t_user_role.id</code>.
     */
    public final TableField<TUserRoleRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.t_user_role.created_at</code>.
     */
    public final TableField<TUserRoleRecord, LocalDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.LOCALDATETIME(6).nullable(false).defaultValue(DSL.field("now()", SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>public.t_user_role.updated_at</code>.
     */
    public final TableField<TUserRoleRecord, LocalDateTime> UPDATED_AT = createField(DSL.name("updated_at"), SQLDataType.LOCALDATETIME(6).nullable(false).defaultValue(DSL.field("now()", SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>public.t_user_role.deleted</code>.
     */
    public final TableField<TUserRoleRecord, Boolean> DELETED = createField(DSL.name("deleted"), SQLDataType.BOOLEAN.nullable(false).defaultValue(DSL.field("false", SQLDataType.BOOLEAN)), this, "");

    /**
     * The column <code>public.t_user_role.user_id</code>.
     */
    public final TableField<TUserRoleRecord, Long> USER_ID = createField(DSL.name("user_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.t_user_role.role_id</code>.
     */
    public final TableField<TUserRoleRecord, Long> ROLE_ID = createField(DSL.name("role_id"), SQLDataType.BIGINT.nullable(false), this, "");

    private TUserRole(Name alias, Table<TUserRoleRecord> aliased) {
        this(alias, aliased, null);
    }

    private TUserRole(Name alias, Table<TUserRoleRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.t_user_role</code> table reference
     */
    public TUserRole(String alias) {
        this(DSL.name(alias), T_USER_ROLE);
    }

    /**
     * Create an aliased <code>public.t_user_role</code> table reference
     */
    public TUserRole(Name alias) {
        this(alias, T_USER_ROLE);
    }

    /**
     * Create a <code>public.t_user_role</code> table reference
     */
    public TUserRole() {
        this(DSL.name("t_user_role"), null);
    }

    public <O extends Record> TUserRole(Table<O> child, ForeignKey<O, TUserRoleRecord> key) {
        super(child, key, T_USER_ROLE);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.T_USER_ROLE_DELETED_USER_ID_IDX);
    }

    @Override
    public Identity<TUserRoleRecord, Long> getIdentity() {
        return (Identity<TUserRoleRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<TUserRoleRecord> getPrimaryKey() {
        return Keys.T_USER_ROLE_PKEY;
    }

    @Override
    public List<ForeignKey<TUserRoleRecord, ?>> getReferences() {
        return Arrays.asList(Keys.T_USER_ROLE__T_USER_ROLE_ROLE_ID_FKEY);
    }

    private transient TRole _tRole;

    public TRole tRole() {
        if (_tRole == null)
            _tRole = new TRole(this, Keys.T_USER_ROLE__T_USER_ROLE_ROLE_ID_FKEY);

        return _tRole;
    }

    @Override
    public TUserRole as(String alias) {
        return new TUserRole(DSL.name(alias), this);
    }

    @Override
    public TUserRole as(Name alias) {
        return new TUserRole(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public TUserRole rename(String name) {
        return new TUserRole(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public TUserRole rename(Name name) {
        return new TUserRole(name, null);
    }

    // -------------------------------------------------------------------------
    // Row6 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row6<Long, LocalDateTime, LocalDateTime, Boolean, Long, Long> fieldsRow() {
        return (Row6) super.fieldsRow();
    }
}
