/*
 * This file is generated by jOOQ.
 */
package com.mvs.repo.tables;


import com.mvs.repo.Indexes;
import com.mvs.repo.Keys;
import com.mvs.repo.Public;
import com.mvs.repo.tables.records.TUserRoleDeletedRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row6;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TUserRoleDeleted extends TableImpl<TUserRoleDeletedRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.t_user_role_deleted</code>
     */
    public static final TUserRoleDeleted T_USER_ROLE_DELETED = new TUserRoleDeleted();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TUserRoleDeletedRecord> getRecordType() {
        return TUserRoleDeletedRecord.class;
    }

    /**
     * The column <code>public.t_user_role_deleted.id</code>.
     */
    public final TableField<TUserRoleDeletedRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.t_user_role_deleted.created_at</code>.
     */
    public final TableField<TUserRoleDeletedRecord, LocalDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.LOCALDATETIME(6).nullable(false).defaultValue(DSL.field("now()", SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>public.t_user_role_deleted.updated_at</code>.
     */
    public final TableField<TUserRoleDeletedRecord, LocalDateTime> UPDATED_AT = createField(DSL.name("updated_at"), SQLDataType.LOCALDATETIME(6).nullable(false).defaultValue(DSL.field("now()", SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>public.t_user_role_deleted.deleted</code>.
     */
    public final TableField<TUserRoleDeletedRecord, Boolean> DELETED = createField(DSL.name("deleted"), SQLDataType.BOOLEAN.nullable(false).defaultValue(DSL.field("false", SQLDataType.BOOLEAN)), this, "");

    /**
     * The column <code>public.t_user_role_deleted.user_id</code>.
     */
    public final TableField<TUserRoleDeletedRecord, Long> USER_ID = createField(DSL.name("user_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.t_user_role_deleted.role_id</code>.
     */
    public final TableField<TUserRoleDeletedRecord, Long> ROLE_ID = createField(DSL.name("role_id"), SQLDataType.BIGINT.nullable(false), this, "");

    private TUserRoleDeleted(Name alias, Table<TUserRoleDeletedRecord> aliased) {
        this(alias, aliased, null);
    }

    private TUserRoleDeleted(Name alias, Table<TUserRoleDeletedRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.t_user_role_deleted</code> table reference
     */
    public TUserRoleDeleted(String alias) {
        this(DSL.name(alias), T_USER_ROLE_DELETED);
    }

    /**
     * Create an aliased <code>public.t_user_role_deleted</code> table reference
     */
    public TUserRoleDeleted(Name alias) {
        this(alias, T_USER_ROLE_DELETED);
    }

    /**
     * Create a <code>public.t_user_role_deleted</code> table reference
     */
    public TUserRoleDeleted() {
        this(DSL.name("t_user_role_deleted"), null);
    }

    public <O extends Record> TUserRoleDeleted(Table<O> child, ForeignKey<O, TUserRoleDeletedRecord> key) {
        super(child, key, T_USER_ROLE_DELETED);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.IDX_USER_ROLE_DELETED, Indexes.T_USER_ROLE_DELETED_DELETED_USER_ID_IDX);
    }

    @Override
    public Identity<TUserRoleDeletedRecord, Long> getIdentity() {
        return (Identity<TUserRoleDeletedRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<TUserRoleDeletedRecord> getPrimaryKey() {
        return Keys.T_USER_ROLE_DELETED_PKEY;
    }

    @Override
    public List<ForeignKey<TUserRoleDeletedRecord, ?>> getReferences() {
        return Arrays.asList(Keys.T_USER_ROLE_DELETED__T_USER_ROLE_ROLE_ID_FKEY);
    }

    private transient TRole _tRole;

    public TRole tRole() {
        if (_tRole == null)
            _tRole = new TRole(this, Keys.T_USER_ROLE_DELETED__T_USER_ROLE_ROLE_ID_FKEY);

        return _tRole;
    }

    @Override
    public TUserRoleDeleted as(String alias) {
        return new TUserRoleDeleted(DSL.name(alias), this);
    }

    @Override
    public TUserRoleDeleted as(Name alias) {
        return new TUserRoleDeleted(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public TUserRoleDeleted rename(String name) {
        return new TUserRoleDeleted(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public TUserRoleDeleted rename(Name name) {
        return new TUserRoleDeleted(name, null);
    }

    // -------------------------------------------------------------------------
    // Row6 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row6<Long, LocalDateTime, LocalDateTime, Boolean, Long, Long> fieldsRow() {
        return (Row6) super.fieldsRow();
    }
}
