/*
 * This file is generated by jOOQ.
 */
package com.mvs.repo.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GetRoleList implements Serializable {

    private static final long serialVersionUID = 1L;

    private final Long   id;
    private final String name;

    public GetRoleList(GetRoleList value) {
        this.id = value.id;
        this.name = value.name;
    }

    public GetRoleList(
        Long   id,
        String name
    ) {
        this.id = id;
        this.name = name;
    }

    /**
     * Getter for <code>public.get_role_list.id</code>.
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Getter for <code>public.get_role_list.name</code>.
     */
    public String getName() {
        return this.name;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("GetRoleList (");

        sb.append(id);
        sb.append(", ").append(name);

        sb.append(")");
        return sb.toString();
    }
}
