/*
 * This file is generated by jOOQ.
 */
package com.mvs.repo.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GetUserRoles implements Serializable {

    private static final long serialVersionUID = 1L;

    private final Long roleId;

    public GetUserRoles(GetUserRoles value) {
        this.roleId = value.roleId;
    }

    public GetUserRoles(
        Long roleId
    ) {
        this.roleId = roleId;
    }

    /**
     * Getter for <code>public.get_user_roles.role_id</code>.
     */
    public Long getRoleId() {
        return this.roleId;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("GetUserRoles (");

        sb.append(roleId);

        sb.append(")");
        return sb.toString();
    }
}
