/*
 * This file is generated by jOOQ.
 */
package com.mvs.repo.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TRole implements Serializable {

    private static final long serialVersionUID = 1L;

    private final Long          id;
    private final LocalDateTime createdAt;
    private final LocalDateTime updatedAt;
    private final String        name;

    public TRole(TRole value) {
        this.id = value.id;
        this.createdAt = value.createdAt;
        this.updatedAt = value.updatedAt;
        this.name = value.name;
    }

    public TRole(
        Long          id,
        LocalDateTime createdAt,
        LocalDateTime updatedAt,
        String        name
    ) {
        this.id = id;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
        this.name = name;
    }

    /**
     * Getter for <code>public.t_role.id</code>.
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Getter for <code>public.t_role.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return this.createdAt;
    }

    /**
     * Getter for <code>public.t_role.updated_at</code>.
     */
    public LocalDateTime getUpdatedAt() {
        return this.updatedAt;
    }

    /**
     * Getter for <code>public.t_role.name</code>.
     */
    public String getName() {
        return this.name;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("TRole (");

        sb.append(id);
        sb.append(", ").append(createdAt);
        sb.append(", ").append(updatedAt);
        sb.append(", ").append(name);

        sb.append(")");
        return sb.toString();
    }
}
