/*
 * This file is generated by jOOQ.
 */
package com.mvs.repo.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TUserRoleActive implements Serializable {

    private static final long serialVersionUID = 1L;

    private final Long          id;
    private final LocalDateTime createdAt;
    private final LocalDateTime updatedAt;
    private final Boolean       deleted;
    private final Long          userId;
    private final Long          roleId;

    public TUserRoleActive(TUserRoleActive value) {
        this.id = value.id;
        this.createdAt = value.createdAt;
        this.updatedAt = value.updatedAt;
        this.deleted = value.deleted;
        this.userId = value.userId;
        this.roleId = value.roleId;
    }

    public TUserRoleActive(
        Long          id,
        LocalDateTime createdAt,
        LocalDateTime updatedAt,
        Boolean       deleted,
        Long          userId,
        Long          roleId
    ) {
        this.id = id;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
        this.deleted = deleted;
        this.userId = userId;
        this.roleId = roleId;
    }

    /**
     * Getter for <code>public.t_user_role_active.id</code>.
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Getter for <code>public.t_user_role_active.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return this.createdAt;
    }

    /**
     * Getter for <code>public.t_user_role_active.updated_at</code>.
     */
    public LocalDateTime getUpdatedAt() {
        return this.updatedAt;
    }

    /**
     * Getter for <code>public.t_user_role_active.deleted</code>.
     */
    public Boolean getDeleted() {
        return this.deleted;
    }

    /**
     * Getter for <code>public.t_user_role_active.user_id</code>.
     */
    public Long getUserId() {
        return this.userId;
    }

    /**
     * Getter for <code>public.t_user_role_active.role_id</code>.
     */
    public Long getRoleId() {
        return this.roleId;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("TUserRoleActive (");

        sb.append(id);
        sb.append(", ").append(createdAt);
        sb.append(", ").append(updatedAt);
        sb.append(", ").append(deleted);
        sb.append(", ").append(userId);
        sb.append(", ").append(roleId);

        sb.append(")");
        return sb.toString();
    }
}
