/*
 * This file is generated by jOOQ.
 */
package com.mvs.repo;


import com.mvs.repo.tables.FlywaySchemaHistory;
import com.mvs.repo.tables.TRole;
import com.mvs.repo.tables.TUserRole;
import com.mvs.repo.tables.TUserRoleActive;
import com.mvs.repo.tables.TUserRoleDeleted;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index FLYWAY_SCHEMA_HISTORY_S_IDX = Internal.createIndex(DSL.name("flyway_schema_history_s_idx"), FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY, new OrderField[] { FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY.SUCCESS }, false);
    public static final Index IDX_USER_ROLE_ACTIVE = Internal.createIndex(DSL.name("idx_user_role_active"), TUserRoleActive.T_USER_ROLE_ACTIVE, new OrderField[] { TUserRoleActive.T_USER_ROLE_ACTIVE.DELETED }, false);
    public static final Index IDX_USER_ROLE_DELETED = Internal.createIndex(DSL.name("idx_user_role_deleted"), TUserRoleDeleted.T_USER_ROLE_DELETED, new OrderField[] { TUserRoleDeleted.T_USER_ROLE_DELETED.DELETED }, false);
    public static final Index T_ROLE_NAME_IDX = Internal.createIndex(DSL.name("t_role_name_idx"), TRole.T_ROLE, new OrderField[] { TRole.T_ROLE.NAME }, true);
    public static final Index T_USER_ROLE_ACTIVE_DELETED_USER_ID_IDX = Internal.createIndex(DSL.name("t_user_role_active_deleted_user_id_idx"), TUserRoleActive.T_USER_ROLE_ACTIVE, new OrderField[] { TUserRoleActive.T_USER_ROLE_ACTIVE.DELETED, TUserRoleActive.T_USER_ROLE_ACTIVE.USER_ID }, false);
    public static final Index T_USER_ROLE_ACTIVE_ROLE_ID_IDX = Internal.createIndex(DSL.name("t_user_role_active_role_id_idx"), TUserRoleActive.T_USER_ROLE_ACTIVE, new OrderField[] { TUserRoleActive.T_USER_ROLE_ACTIVE.ROLE_ID }, true);
    public static final Index T_USER_ROLE_ACTIVE_USER_ID_ROLE_ID_IDX = Internal.createIndex(DSL.name("t_user_role_active_user_id_role_id_idx"), TUserRoleActive.T_USER_ROLE_ACTIVE, new OrderField[] { TUserRoleActive.T_USER_ROLE_ACTIVE.USER_ID, TUserRoleActive.T_USER_ROLE_ACTIVE.ROLE_ID }, true);
    public static final Index T_USER_ROLE_DELETED_DELETED_USER_ID_IDX = Internal.createIndex(DSL.name("t_user_role_deleted_deleted_user_id_idx"), TUserRoleDeleted.T_USER_ROLE_DELETED, new OrderField[] { TUserRoleDeleted.T_USER_ROLE_DELETED.DELETED, TUserRoleDeleted.T_USER_ROLE_DELETED.USER_ID }, false);
    public static final Index T_USER_ROLE_DELETED_USER_ID_IDX = Internal.createIndex(DSL.name("t_user_role_deleted_user_id_idx"), TUserRole.T_USER_ROLE, new OrderField[] { TUserRole.T_USER_ROLE.DELETED, TUserRole.T_USER_ROLE.USER_ID }, false);
}
