/*
 * This file is generated by jOOQ.
 */
package com.mvs.repo;


import com.mvs.repo.tables.FlywaySchemaHistory;
import com.mvs.repo.tables.TRole;
import com.mvs.repo.tables.TUserRole;
import com.mvs.repo.tables.TUserRoleActive;
import com.mvs.repo.tables.TUserRoleDeleted;
import com.mvs.repo.tables.records.FlywaySchemaHistoryRecord;
import com.mvs.repo.tables.records.TRoleRecord;
import com.mvs.repo.tables.records.TUserRoleActiveRecord;
import com.mvs.repo.tables.records.TUserRoleDeletedRecord;
import com.mvs.repo.tables.records.TUserRoleRecord;

import org.jooq.ForeignKey;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in
 * public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<FlywaySchemaHistoryRecord> FLYWAY_SCHEMA_HISTORY_PK = Internal.createUniqueKey(FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY, DSL.name("flyway_schema_history_pk"), new TableField[] { FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY.INSTALLED_RANK }, true);
    public static final UniqueKey<TRoleRecord> T_ROLE_PKEY = Internal.createUniqueKey(TRole.T_ROLE, DSL.name("t_role_pkey"), new TableField[] { TRole.T_ROLE.ID }, true);
    public static final UniqueKey<TUserRoleRecord> T_USER_ROLE_PKEY = Internal.createUniqueKey(TUserRole.T_USER_ROLE, DSL.name("t_user_role_pkey"), new TableField[] { TUserRole.T_USER_ROLE.ID, TUserRole.T_USER_ROLE.DELETED }, true);
    public static final UniqueKey<TUserRoleActiveRecord> T_USER_ROLE_ACTIVE_PKEY = Internal.createUniqueKey(TUserRoleActive.T_USER_ROLE_ACTIVE, DSL.name("t_user_role_active_pkey"), new TableField[] { TUserRoleActive.T_USER_ROLE_ACTIVE.ID, TUserRoleActive.T_USER_ROLE_ACTIVE.DELETED }, true);
    public static final UniqueKey<TUserRoleDeletedRecord> T_USER_ROLE_DELETED_PKEY = Internal.createUniqueKey(TUserRoleDeleted.T_USER_ROLE_DELETED, DSL.name("t_user_role_deleted_pkey"), new TableField[] { TUserRoleDeleted.T_USER_ROLE_DELETED.ID, TUserRoleDeleted.T_USER_ROLE_DELETED.DELETED }, true);

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<TUserRoleRecord, TRoleRecord> T_USER_ROLE__T_USER_ROLE_ROLE_ID_FKEY = Internal.createForeignKey(TUserRole.T_USER_ROLE, DSL.name("t_user_role_role_id_fkey"), new TableField[] { TUserRole.T_USER_ROLE.ROLE_ID }, Keys.T_ROLE_PKEY, new TableField[] { TRole.T_ROLE.ID }, true);
    public static final ForeignKey<TUserRoleActiveRecord, TRoleRecord> T_USER_ROLE_ACTIVE__T_USER_ROLE_ROLE_ID_FKEY = Internal.createForeignKey(TUserRoleActive.T_USER_ROLE_ACTIVE, DSL.name("t_user_role_role_id_fkey"), new TableField[] { TUserRoleActive.T_USER_ROLE_ACTIVE.ROLE_ID }, Keys.T_ROLE_PKEY, new TableField[] { TRole.T_ROLE.ID }, true);
    public static final ForeignKey<TUserRoleDeletedRecord, TRoleRecord> T_USER_ROLE_DELETED__T_USER_ROLE_ROLE_ID_FKEY = Internal.createForeignKey(TUserRoleDeleted.T_USER_ROLE_DELETED, DSL.name("t_user_role_role_id_fkey"), new TableField[] { TUserRoleDeleted.T_USER_ROLE_DELETED.ROLE_ID }, Keys.T_ROLE_PKEY, new TableField[] { TRole.T_ROLE.ID }, true);
}
