/*
 * This file is generated by jOOQ.
 */
package com.mvs.repo;


import com.mvs.repo.tables.FlywaySchemaHistory;
import com.mvs.repo.tables.GetRoleList;
import com.mvs.repo.tables.GetUserRoles;
import com.mvs.repo.tables.TRole;
import com.mvs.repo.tables.TUserRole;
import com.mvs.repo.tables.TUserRoleActive;
import com.mvs.repo.tables.TUserRoleDeleted;
import com.mvs.repo.tables.records.GetRoleListRecord;
import com.mvs.repo.tables.records.GetUserRolesRecord;

import org.jooq.Configuration;
import org.jooq.Field;
import org.jooq.Result;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.flyway_schema_history</code>.
     */
    public static final FlywaySchemaHistory FLYWAY_SCHEMA_HISTORY = FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY;

    /**
     * The table <code>public.get_role_list</code>.
     */
    public static final GetRoleList GET_ROLE_LIST = GetRoleList.GET_ROLE_LIST;

    /**
     * Call <code>public.get_role_list</code>.
     */
    public static Result<GetRoleListRecord> GET_ROLE_LIST(
          Configuration configuration
    ) {
        return configuration.dsl().selectFrom(com.mvs.repo.tables.GetRoleList.GET_ROLE_LIST.call(
        )).fetch();
    }

    /**
     * Get <code>public.get_role_list</code> as a table.
     */
    public static GetRoleList GET_ROLE_LIST() {
        return com.mvs.repo.tables.GetRoleList.GET_ROLE_LIST.call(
        );
    }

    /**
     * The table <code>public.get_user_roles</code>.
     */
    public static final GetUserRoles GET_USER_ROLES = GetUserRoles.GET_USER_ROLES;

    /**
     * Call <code>public.get_user_roles</code>.
     */
    public static Result<GetUserRolesRecord> GET_USER_ROLES(
          Configuration configuration
        , Long pUserId
    ) {
        return configuration.dsl().selectFrom(com.mvs.repo.tables.GetUserRoles.GET_USER_ROLES.call(
              pUserId
        )).fetch();
    }

    /**
     * Get <code>public.get_user_roles</code> as a table.
     */
    public static GetUserRoles GET_USER_ROLES(
          Long pUserId
    ) {
        return com.mvs.repo.tables.GetUserRoles.GET_USER_ROLES.call(
            pUserId
        );
    }

    /**
     * Get <code>public.get_user_roles</code> as a table.
     */
    public static GetUserRoles GET_USER_ROLES(
          Field<Long> pUserId
    ) {
        return com.mvs.repo.tables.GetUserRoles.GET_USER_ROLES.call(
            pUserId
        );
    }

    /**
     * The table <code>public.t_role</code>.
     */
    public static final TRole T_ROLE = TRole.T_ROLE;

    /**
     * The table <code>public.t_user_role</code>.
     */
    public static final TUserRole T_USER_ROLE = TUserRole.T_USER_ROLE;

    /**
     * The table <code>public.t_user_role_active</code>.
     */
    public static final TUserRoleActive T_USER_ROLE_ACTIVE = TUserRoleActive.T_USER_ROLE_ACTIVE;

    /**
     * The table <code>public.t_user_role_deleted</code>.
     */
    public static final TUserRoleDeleted T_USER_ROLE_DELETED = TUserRoleDeleted.T_USER_ROLE_DELETED;
}
